import React from 'react';

import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

export function DisclaimerScreen({ colors, onContinue ,onBack}) {
  return (
    <ScrollView
      style={[
        styles.container,
        {
          backgroundColor: colors.background,
        },
      ]}
      contentContainerStyle={styles.content}
      showsVerticalScrollIndicator={false}
    >
      <Pressable onPress={onBack} style={styles.backButton}>
        <Text style={[styles.backText, { color: colors.primary }]}>‹ Back</Text>
      </Pressable>
      <Text
        style={[
          styles.title,
          {
            color: colors.onBackground,
          },
        ]}
      >
        Before you begin
      </Text>

      <Text
        style={[
          styles.subtitle,
          {
            color: colors.onSurfaceVariant,
          },
        ]}
      >
        Please read this important information before starting a new diagnosis.
      </Text>

      {/* Disclaimer Card */}

      <View
        style={[
          styles.card,
          {
            backgroundColor: colors.surface,
            borderColor: colors.outlineVariant,
          },
        ]}
      >
        <View
          style={[
            styles.iconContainer,
            {
              backgroundColor: colors.primaryContainer,
            },
          ]}
        >
          <Text
            style={[
              styles.icon,
              {
                color: colors.onPrimaryContainer,
              },
            ]}
          >
            i
          </Text>
        </View>

        <Text
          style={[
            styles.cardTitle,
            {
              color: colors.onSurface,
            },
          ]}
        >
          Research and screening tool
        </Text>

        <Text
          style={[
            styles.body,
            {
              color: colors.onSurfaceVariant,
            },
          ]}
        >
          OralScan uses machine learning models to assist with oral image and
          vocal screening.
        </Text>

        <Text
          style={[
            styles.body,
            {
              color: colors.onSurfaceVariant,
            },
          ]}
        >
          The results generated by this application are for research and
          screening purposes only. They are not a medical diagnosis and should
          not be used as a substitute for professional medical advice,
          diagnosis, or treatment.
        </Text>

        <Text
          style={[
            styles.body,
            {
              color: colors.onSurfaceVariant,
            },
          ]}
        >
          A qualified healthcare professional should review any concerning
          results and determine appropriate clinical evaluation.
        </Text>
      </View>

      {/* What happens next */}

      <Text
        style={[
          styles.sectionTitle,
          {
            color: colors.onBackground,
          },
        ]}
      >
        What happens next?
      </Text>

      <View style={styles.steps}>
        <Step
          number="1"
          title="Patient details"
          description="Enter basic information for the diagnosis report."
          colors={colors}
        />

        <Step
          number="2"
          title="Image and voice analysis"
          description="Run either or both available screening methods."
          colors={colors}
        />

        <Step
          number="3"
          title="Generate report"
          description="Review the available results in a combined report."
          colors={colors}
        />
      </View>

      {/* Continue */}

      <Pressable
        onPress={onContinue}
        style={({ pressed }) => [
          styles.continueButton,
          {
            backgroundColor: colors.primary,
            opacity: pressed ? 0.85 : 1,
          },
        ]}
      >
        <Text
          style={[
            styles.continueText,
            {
              color: colors.onPrimary,
            },
          ]}
        >
          I Understand & Continue
        </Text>
      </Pressable>

      <Text
        style={[
          styles.footer,
          {
            color: colors.onSurfaceVariant,
          },
        ]}
      >
        By continuing, you acknowledge that you understand the purpose and
        limitations of this application.
      </Text>
    </ScrollView>
  );
}

function Step({ number, title, description, colors }) {
  return (
    <View style={styles.step}>
      <View
        style={[
          styles.stepNumber,
          {
            backgroundColor: colors.primaryContainer,
          },
        ]}
      >
        <Text
          style={{
            color: colors.onPrimaryContainer,
            fontSize: 13,
            fontWeight: '700',
          }}
        >
          {number}
        </Text>
      </View>

      <View style={styles.stepContent}>
        <Text
          style={[
            styles.stepTitle,
            {
              color: colors.onSurface,
            },
          ]}
        >
          {title}
        </Text>

        <Text
          style={[
            styles.stepDescription,
            {
              color: colors.onSurfaceVariant,
            },
          ]}
        >
          {description}
        </Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },

  content: {
    paddingHorizontal: 24,
    paddingTop: 5,
    paddingBottom: 40,
  },

  logoContainer: {
    alignItems: 'center',
    marginBottom: 28,
  },

  logoCircle: {
    width: 64,
    height: 64,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
  },

  logo: {
    fontSize: 38,
    fontWeight: '700',
  },

  title: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600',
    textAlign: 'center',
  },

  subtitle: {
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 28,
  },

  card: {
    borderWidth: 1,
    borderRadius: 24,
    padding: 22,
  },

  iconContainer: {
    width: 42,
    height: 42,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },

  icon: {
    fontSize: 22,
    fontWeight: '700',
  },

  cardTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '600',
    marginBottom: 10,
  },

  body: {
    fontSize: 14,
    lineHeight: 21,
    marginBottom: 12,
  },

  sectionTitle: {
    fontSize: 19,
    lineHeight: 26,
    fontWeight: '600',
    marginTop: 30,
    marginBottom: 16,
  },

  steps: {
    gap: 16,
  },

  step: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },

  stepNumber: {
    width: 30,
    height: 30,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },

  stepContent: {
    flex: 1,
    marginLeft: 12,
  },

  stepTitle: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
  },

  stepDescription: {
    fontSize: 12,
    lineHeight: 17,
    marginTop: 2,
  },

  continueButton: {
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 32,
  },

  continueText: {
    fontSize: 15,
    fontWeight: '600',
  },

  footer: {
    fontSize: 11,
    lineHeight: 16,
    textAlign: 'center',
    marginTop: 12,
    paddingHorizontal: 10,
  },
});

export default DisclaimerScreen;
